title: ''
baseURL: "https://ataraxxis.github.io/workshops/"
theme: PaperModX

enableRobotsTXT: true
enableEmoji: true

params:
  description: "Miniatur Malworkshops Deutschland"
  author: Jonas Doese
  images:
    - cover.png
  favicon: favicon.ico
  #logo:
  #  icon: images/logo.svg
  #DateFormat: "2006-01-02"
  DateFormat: "2 Jan 2006"
  useCustomAnalytics: true
  mainSections:
    - posts
    - notes

  # theme params
  DisableLanguageSwitch: true
  TocOpen: false
  TocSide: right
  EnableInstantClick: false
  EnableImageZoom: true
  ShowShareButtons: false
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: false
  ShowWordCount: false
  ShowCodeCopyButtons: false
  ShowPostNavLinks: false
  Email: info@ruhrartminiatures.com

  #socialIcons:
  #  - name: github-simple
  #    url: "https://github.com/reorx"
  #  - name: twitter-simple
  #    url: "https://twitter.com/novoreorx"
  #  - name: telegram-simple
  #    url: "https://t.me/reorx_share"
  #  - name: rss-simple
  #    url: "feed.xml"
  #  - name: gmail
  #    url: email

  #socialAccounts:
  #  twitter:
  #    username: novoreorx

  homeInfoParams:
    Title: "Miniatur Malworkshops Deutschland"
    Content: |
      Hier findet ihr eine Übersicht über Malworkshops in Deutschland

  #commentSystems:
  #  disqus:
  #    shortname: reorx
  #  remark42:
  #    url: https://remark42.reorx.com
  #    site: reorx.github.io
  #  telegramWidget:
  #    channel: reorx_share
  #    accentColor: "9077e1"
  #    limit: 20
  #defaultCommentSystems:
  #  remark42: true

permalinks:
  notes: /:section/:year/:month/:slugorfilename

# prefer feed.xml rather than index.xml
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

menu:
  main:
    - name: Home
      url: /
      weight: 1

languages:
  en:
    languageName: "English"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
